/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BookMarketplace {
  export type BookStruct = {
    id: BigNumberish;
    title: string;
    author: string;
    priceInTokens: BigNumberish;
    metadataURI: string;
    active: boolean;
    totalSales: BigNumberish;
  };

  export type BookStructOutput = [
    id: bigint,
    title: string,
    author: string,
    priceInTokens: bigint,
    metadataURI: string,
    active: boolean,
    totalSales: bigint
  ] & {
    id: bigint;
    title: string;
    author: string;
    priceInTokens: bigint;
    metadataURI: string;
    active: boolean;
    totalSales: bigint;
  };

  export type UserStruct = {
    registered: boolean;
    username: string;
    purchasedBooks: BigNumberish;
    registeredAt: BigNumberish;
  };

  export type UserStructOutput = [
    registered: boolean,
    username: string,
    purchasedBooks: bigint,
    registeredAt: bigint
  ] & {
    registered: boolean;
    username: string;
    purchasedBooks: bigint;
    registeredAt: bigint;
  };
}

export interface BookMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TOKENS_PER_ETH"
      | "TOKEN_UNIT"
      | "accumulatedTokenRevenue"
      | "bookNFT"
      | "books"
      | "buyBook"
      | "buyTokens"
      | "createBook"
      | "getBook"
      | "getBookNFTAddress"
      | "getMyAllowanceToMarketplace"
      | "getMyTokenBalance"
      | "getPaymentTokenAddress"
      | "getTokenAllowance"
      | "getTokenBalance"
      | "getUser"
      | "hasUserBook"
      | "isRegistered"
      | "nextBookId"
      | "owner"
      | "ownsBook"
      | "paymentToken"
      | "register"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateBook"
      | "updateUsername"
      | "users"
      | "withdrawETH"
      | "withdrawTokenRevenue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BookCreated"
      | "BookPurchased"
      | "BookUpdated"
      | "EthWithdrawn"
      | "OwnershipTransferred"
      | "TokenRevenueWithdrawn"
      | "TokensPurchased"
      | "UserRegistered"
      | "UsernameUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TOKENS_PER_ETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_UNIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedTokenRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bookNFT", values?: undefined): string;
  encodeFunctionData(functionFragment: "books", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "buyBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "buyTokens", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createBook",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookNFTAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyAllowanceToMarketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyTokenBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAllowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserBook",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBookId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownsBook",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "register", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBook",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUsername",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokenRevenue",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "TOKENS_PER_ETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TOKEN_UNIT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedTokenRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bookNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "books", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyBook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createBook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBookNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyAllowanceToMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasUserBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextBookId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownsBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateBook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokenRevenue",
    data: BytesLike
  ): Result;
}

export namespace BookCreatedEvent {
  export type InputTuple = [
    bookId: BigNumberish,
    title: string,
    author: string,
    priceInTokens: BigNumberish
  ];
  export type OutputTuple = [
    bookId: bigint,
    title: string,
    author: string,
    priceInTokens: bigint
  ];
  export interface OutputObject {
    bookId: bigint;
    title: string;
    author: string;
    priceInTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    bookId: BigNumberish,
    priceInTokens: BigNumberish,
    nftTokenId: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    bookId: bigint,
    priceInTokens: bigint,
    nftTokenId: bigint
  ];
  export interface OutputObject {
    buyer: string;
    bookId: bigint;
    priceInTokens: bigint;
    nftTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookUpdatedEvent {
  export type InputTuple = [
    bookId: BigNumberish,
    newPriceInTokens: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    bookId: bigint,
    newPriceInTokens: bigint,
    active: boolean
  ];
  export interface OutputObject {
    bookId: bigint;
    newPriceInTokens: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRevenueWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    ethPaid: BigNumberish,
    tokensReceived: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    ethPaid: bigint,
    tokensReceived: bigint
  ];
  export interface OutputObject {
    buyer: string;
    ethPaid: bigint;
    tokensReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, username: string];
  export type OutputTuple = [user: string, username: string];
  export interface OutputObject {
    user: string;
    username: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsernameUpdatedEvent {
  export type InputTuple = [user: AddressLike, newUsername: string];
  export type OutputTuple = [user: string, newUsername: string];
  export interface OutputObject {
    user: string;
    newUsername: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BookMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): BookMarketplace;
  waitForDeployment(): Promise<this>;

  interface: BookMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TOKENS_PER_ETH: TypedContractMethod<[], [bigint], "view">;

  TOKEN_UNIT: TypedContractMethod<[], [bigint], "view">;

  accumulatedTokenRevenue: TypedContractMethod<[], [bigint], "view">;

  bookNFT: TypedContractMethod<[], [string], "view">;

  books: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, boolean, bigint] & {
        id: bigint;
        title: string;
        author: string;
        priceInTokens: bigint;
        metadataURI: string;
        active: boolean;
        totalSales: bigint;
      }
    ],
    "view"
  >;

  buyBook: TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;

  buyTokens: TypedContractMethod<[], [void], "payable">;

  createBook: TypedContractMethod<
    [
      title: string,
      author: string,
      priceInTokens: BigNumberish,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  getBook: TypedContractMethod<
    [bookId: BigNumberish],
    [BookMarketplace.BookStructOutput],
    "view"
  >;

  getBookNFTAddress: TypedContractMethod<[], [string], "view">;

  getMyAllowanceToMarketplace: TypedContractMethod<[], [bigint], "view">;

  getMyTokenBalance: TypedContractMethod<[], [bigint], "view">;

  getPaymentTokenAddress: TypedContractMethod<[], [string], "view">;

  getTokenAllowance: TypedContractMethod<
    [owner_: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  getTokenBalance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUser: TypedContractMethod<
    [user: AddressLike],
    [BookMarketplace.UserStructOutput],
    "view"
  >;

  hasUserBook: TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish],
    [boolean],
    "view"
  >;

  isRegistered: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  nextBookId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownsBook: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  paymentToken: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<[username: string], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBook: TypedContractMethod<
    [bookId: BigNumberish, newPriceInTokens: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  updateUsername: TypedContractMethod<
    [newUsername: string],
    [void],
    "nonpayable"
  >;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, bigint, bigint] & {
        registered: boolean;
        username: string;
        purchasedBooks: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  withdrawETH: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawTokenRevenue: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TOKENS_PER_ETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_UNIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accumulatedTokenRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bookNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "books"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, boolean, bigint] & {
        id: bigint;
        title: string;
        author: string;
        priceInTokens: bigint;
        metadataURI: string;
        active: boolean;
        totalSales: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "buyBook"
  ): TypedContractMethod<[bookId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buyTokens"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "createBook"
  ): TypedContractMethod<
    [
      title: string,
      author: string,
      priceInTokens: BigNumberish,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBook"
  ): TypedContractMethod<
    [bookId: BigNumberish],
    [BookMarketplace.BookStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBookNFTAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyAllowanceToMarketplace"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyTokenBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPaymentTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenAllowance"
  ): TypedContractMethod<
    [owner_: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [user: AddressLike],
    [BookMarketplace.UserStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserBook"
  ): TypedContractMethod<
    [user: AddressLike, bookId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextBookId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownsBook"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[username: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBook"
  ): TypedContractMethod<
    [bookId: BigNumberish, newPriceInTokens: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUsername"
  ): TypedContractMethod<[newUsername: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, bigint, bigint] & {
        registered: boolean;
        username: string;
        purchasedBooks: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawTokenRevenue"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BookCreated"
  ): TypedContractEvent<
    BookCreatedEvent.InputTuple,
    BookCreatedEvent.OutputTuple,
    BookCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BookPurchased"
  ): TypedContractEvent<
    BookPurchasedEvent.InputTuple,
    BookPurchasedEvent.OutputTuple,
    BookPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "BookUpdated"
  ): TypedContractEvent<
    BookUpdatedEvent.InputTuple,
    BookUpdatedEvent.OutputTuple,
    BookUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EthWithdrawn"
  ): TypedContractEvent<
    EthWithdrawnEvent.InputTuple,
    EthWithdrawnEvent.OutputTuple,
    EthWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenRevenueWithdrawn"
  ): TypedContractEvent<
    TokenRevenueWithdrawnEvent.InputTuple,
    TokenRevenueWithdrawnEvent.OutputTuple,
    TokenRevenueWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "UsernameUpdated"
  ): TypedContractEvent<
    UsernameUpdatedEvent.InputTuple,
    UsernameUpdatedEvent.OutputTuple,
    UsernameUpdatedEvent.OutputObject
  >;

  filters: {
    "BookCreated(uint256,string,string,uint256)": TypedContractEvent<
      BookCreatedEvent.InputTuple,
      BookCreatedEvent.OutputTuple,
      BookCreatedEvent.OutputObject
    >;
    BookCreated: TypedContractEvent<
      BookCreatedEvent.InputTuple,
      BookCreatedEvent.OutputTuple,
      BookCreatedEvent.OutputObject
    >;

    "BookPurchased(address,uint256,uint256,uint256)": TypedContractEvent<
      BookPurchasedEvent.InputTuple,
      BookPurchasedEvent.OutputTuple,
      BookPurchasedEvent.OutputObject
    >;
    BookPurchased: TypedContractEvent<
      BookPurchasedEvent.InputTuple,
      BookPurchasedEvent.OutputTuple,
      BookPurchasedEvent.OutputObject
    >;

    "BookUpdated(uint256,uint256,bool)": TypedContractEvent<
      BookUpdatedEvent.InputTuple,
      BookUpdatedEvent.OutputTuple,
      BookUpdatedEvent.OutputObject
    >;
    BookUpdated: TypedContractEvent<
      BookUpdatedEvent.InputTuple,
      BookUpdatedEvent.OutputTuple,
      BookUpdatedEvent.OutputObject
    >;

    "EthWithdrawn(address,uint256)": TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;
    EthWithdrawn: TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenRevenueWithdrawn(address,uint256)": TypedContractEvent<
      TokenRevenueWithdrawnEvent.InputTuple,
      TokenRevenueWithdrawnEvent.OutputTuple,
      TokenRevenueWithdrawnEvent.OutputObject
    >;
    TokenRevenueWithdrawn: TypedContractEvent<
      TokenRevenueWithdrawnEvent.InputTuple,
      TokenRevenueWithdrawnEvent.OutputTuple,
      TokenRevenueWithdrawnEvent.OutputObject
    >;

    "TokensPurchased(address,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "UserRegistered(address,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;

    "UsernameUpdated(address,string)": TypedContractEvent<
      UsernameUpdatedEvent.InputTuple,
      UsernameUpdatedEvent.OutputTuple,
      UsernameUpdatedEvent.OutputObject
    >;
    UsernameUpdated: TypedContractEvent<
      UsernameUpdatedEvent.InputTuple,
      UsernameUpdatedEvent.OutputTuple,
      UsernameUpdatedEvent.OutputObject
    >;
  };
}
